title:            Game Developers Club Of CEG
description:      Official Blog of GDC (Game Developers Club Of CEG)
disqus_shortname: GDC-CEG
# Your site's domain goes here. When working locally use localhost server leave blank
# PS. If you set this wrong stylesheets and scripts won't load and most links will break.
# PPS. If you leave it blank for local testing home links won't work, they'll be fine for live domains though.
url:              http://gdc-ceg.github.io

# Owner/author information
owner:
  name:           GDC-CEG
  avatar:         
  bio:            A discussion platform for everyone who likes to know and learn about Game development which includes Graphics, AI and Game Physics.
  email:          ksashikumark93@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:      https://www.facebook.com/groups/1374494039453422/ 
  github:        https://github.com/GDC-CEG 
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Calcutta
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 5
